version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb-kanban-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: mongodb-kanban-server
    volumes:
      - "./dist:/server/dist"